// bench_macro_vs_reflection.cpp — compile-time / binary-size benchmark:
// user-facing macro (NLOHMANN_DEFINE_TYPE_INTRUSIVE) vs a generic P2996
// reflection serializer (template for over nonstatic_data_members_of).
//
// Same TU, same standard and flags in both modes — only the serializer source
// differs, selected by -DBENCH_REFLECTION:
//
//   macro mode:      g++-16 -std=c++26 -freflection -O0 -DBENCH_N=50 -Iinclude \
//                      -o /tmp/bench_macro bench_macro_vs_reflection.cpp
//   reflection mode: g++-16 -std=c++26 -freflection -O0 -DBENCH_N=50 \
//                      -DBENCH_REFLECTION -Iinclude \
//                      -o /tmp/bench_refl bench_macro_vs_reflection.cpp
//
// BENCH_N (default 50) = how many person-like structs are actually
// instantiated in main(); all 100 definitions are always present, but unused
// types generate no code, so -DBENCH_N sweeps the marginal cost.
//
// person-like struct: { name, age, height, tags, active } — the five field
// types used for the lines-per-type table in EVALUATION.md §2.2.
//
// Measure with:
//   /usr/bin/time -f "wall=%e s maxrss=%M KB" g++-16 ...   (compile)
//   size <exe> | tail -1                                   (text/data/bss)
//   nm <exe> | wc -l                                       (symbol count)
#include <cstdio>
#include <string>
#include <vector>

#include <nlohmann/json.hpp>

#ifdef BENCH_REFLECTION
    #include <meta>
#endif

using json = nlohmann::json;

// ---------------------------------------------------------------------------
// The generic reflection serializer — the one-time cost. The `namespace refl`
// block below is 24 lines; plus 1 `#include <meta>` = the 25-line one-time
// cost used in the lines-per-type arithmetic of EVALUATION.md §2.2 (the
// break-even is at N = 25 types).
// ---------------------------------------------------------------------------
#ifdef BENCH_REFLECTION
namespace refl
{
template<typename BasicJsonType, typename T>
void to_json(BasicJsonType& j, const T& v)
{
    j = BasicJsonType::object();
    template for (constexpr auto m : std::define_static_array(
        std::meta::nonstatic_data_members_of(^^T, std::meta::access_context::unprivileged())))
    {
        j[std::string(std::meta::identifier_of(m))] = v.[:m:];
    }
}

template<typename BasicJsonType, typename T>
void from_json(const BasicJsonType& j, T& v)
{
    template for (constexpr auto m : std::define_static_array(
        std::meta::nonstatic_data_members_of(^^T, std::meta::access_context::unprivileged())))
    {
        using M = typename [: std::meta::type_of(m) :];
        v.[:m:] = j.at(std::string(std::meta::identifier_of(m))).template get<M>();
    }
}
}
#endif

// ---------------------------------------------------------------------------
// 100 person-like structs, generated by the PERSON() X-macro. In macro mode
// each also gets NLOHMANN_DEFINE_TYPE_INTRUSIVE; in reflection mode the plain
// struct is all the user writes.
// ---------------------------------------------------------------------------
#define PERSON_FIELDS \
    std::string name; \
    int age; \
    double height; \
    std::vector<std::string> tags; \
    bool active;

#ifdef BENCH_REFLECTION
    #define DEFINE_PERSON(i) struct person_##i \
    { \
        PERSON_FIELDS \
    };
#else
    // intrusive: the NLOHMANN_DEFINE_TYPE_INTRUSIVE call lives INSIDE the class
    // body (it defines friend to_json/from_json); per-type user cost = 1 struct
    // line + 1 macro line (the field lines are common to both modes)
    #define DEFINE_PERSON(i) struct person_##i \
    { \
        NLOHMANN_DEFINE_TYPE_INTRUSIVE(person_##i, name, age, height, tags, active) \
        PERSON_FIELDS \
    };
#endif

#define PERSON(i) DEFINE_PERSON(i)
#define PERSON(i) DEFINE_PERSON(i)
PERSON(0)
PERSON(1)
PERSON(2)
PERSON(3)
PERSON(4)
PERSON(5)
PERSON(6)
PERSON(7)
PERSON(8)
PERSON(9)
PERSON(10)
PERSON(11)
PERSON(12)
PERSON(13)
PERSON(14)
PERSON(15)
PERSON(16)
PERSON(17)
PERSON(18)
PERSON(19)
PERSON(20)
PERSON(21)
PERSON(22)
PERSON(23)
PERSON(24)
PERSON(25)
PERSON(26)
PERSON(27)
PERSON(28)
PERSON(29)
PERSON(30)
PERSON(31)
PERSON(32)
PERSON(33)
PERSON(34)
PERSON(35)
PERSON(36)
PERSON(37)
PERSON(38)
PERSON(39)
PERSON(40)
PERSON(41)
PERSON(42)
PERSON(43)
PERSON(44)
PERSON(45)
PERSON(46)
PERSON(47)
PERSON(48)
PERSON(49)
PERSON(50)
PERSON(51)
PERSON(52)
PERSON(53)
PERSON(54)
PERSON(55)
PERSON(56)
PERSON(57)
PERSON(58)
PERSON(59)
PERSON(60)
PERSON(61)
PERSON(62)
PERSON(63)
PERSON(64)
PERSON(65)
PERSON(66)
PERSON(67)
PERSON(68)
PERSON(69)
PERSON(70)
PERSON(71)
PERSON(72)
PERSON(73)
PERSON(74)
PERSON(75)
PERSON(76)
PERSON(77)
PERSON(78)
PERSON(79)
PERSON(80)
PERSON(81)
PERSON(82)
PERSON(83)
PERSON(84)
PERSON(85)
PERSON(86)
PERSON(87)
PERSON(88)
PERSON(89)
PERSON(90)
PERSON(91)
PERSON(92)
PERSON(93)
PERSON(94)
PERSON(95)
PERSON(96)
PERSON(97)
PERSON(98)
PERSON(99)
#undef PERSON

// ---------------------------------------------------------------------------
// Preprocessor recursion: expand USE(0) USE(1) ... USE(BENCH_N-1).
// ---------------------------------------------------------------------------
#ifndef BENCH_N
    #define BENCH_N 50
#endif
#define CAT_(a, b) a##b
#define CAT(a, b) CAT_(a, b)
#define EMPTY()
#define DEFER(id) id EMPTY()
#define EXPAND(...) EXPAND1(EXPAND1(EXPAND1(EXPAND1(__VA_ARGS__))))
#define EXPAND1(...) EXPAND2(EXPAND2(EXPAND2(EXPAND2(__VA_ARGS__))))
#define EXPAND2(...) EXPAND3(EXPAND3(EXPAND3(EXPAND3(__VA_ARGS__))))
#define EXPAND3(...) EXPAND4(EXPAND4(EXPAND4(EXPAND4(__VA_ARGS__))))
#define EXPAND4(...) __VA_ARGS__
// ---- GENERATED BLOCK (USE_ALL_0..USE_ALL_100) — do not hand-edit ----
#define USE_ALL_0()
#define USE_ALL_1() USE_ALL_0() USE(0)
#define USE_ALL_2() USE_ALL_1() USE(1)
#define USE_ALL_3() USE_ALL_2() USE(2)
#define USE_ALL_4() USE_ALL_3() USE(3)
#define USE_ALL_5() USE_ALL_4() USE(4)
#define USE_ALL_6() USE_ALL_5() USE(5)
#define USE_ALL_7() USE_ALL_6() USE(6)
#define USE_ALL_8() USE_ALL_7() USE(7)
#define USE_ALL_9() USE_ALL_8() USE(8)
#define USE_ALL_10() USE_ALL_9() USE(9)
#define USE_ALL_11() USE_ALL_10() USE(10)
#define USE_ALL_12() USE_ALL_11() USE(11)
#define USE_ALL_13() USE_ALL_12() USE(12)
#define USE_ALL_14() USE_ALL_13() USE(13)
#define USE_ALL_15() USE_ALL_14() USE(14)
#define USE_ALL_16() USE_ALL_15() USE(15)
#define USE_ALL_17() USE_ALL_16() USE(16)
#define USE_ALL_18() USE_ALL_17() USE(17)
#define USE_ALL_19() USE_ALL_18() USE(18)
#define USE_ALL_20() USE_ALL_19() USE(19)
#define USE_ALL_21() USE_ALL_20() USE(20)
#define USE_ALL_22() USE_ALL_21() USE(21)
#define USE_ALL_23() USE_ALL_22() USE(22)
#define USE_ALL_24() USE_ALL_23() USE(23)
#define USE_ALL_25() USE_ALL_24() USE(24)
#define USE_ALL_26() USE_ALL_25() USE(25)
#define USE_ALL_27() USE_ALL_26() USE(26)
#define USE_ALL_28() USE_ALL_27() USE(27)
#define USE_ALL_29() USE_ALL_28() USE(28)
#define USE_ALL_30() USE_ALL_29() USE(29)
#define USE_ALL_31() USE_ALL_30() USE(30)
#define USE_ALL_32() USE_ALL_31() USE(31)
#define USE_ALL_33() USE_ALL_32() USE(32)
#define USE_ALL_34() USE_ALL_33() USE(33)
#define USE_ALL_35() USE_ALL_34() USE(34)
#define USE_ALL_36() USE_ALL_35() USE(35)
#define USE_ALL_37() USE_ALL_36() USE(36)
#define USE_ALL_38() USE_ALL_37() USE(37)
#define USE_ALL_39() USE_ALL_38() USE(38)
#define USE_ALL_40() USE_ALL_39() USE(39)
#define USE_ALL_41() USE_ALL_40() USE(40)
#define USE_ALL_42() USE_ALL_41() USE(41)
#define USE_ALL_43() USE_ALL_42() USE(42)
#define USE_ALL_44() USE_ALL_43() USE(43)
#define USE_ALL_45() USE_ALL_44() USE(44)
#define USE_ALL_46() USE_ALL_45() USE(45)
#define USE_ALL_47() USE_ALL_46() USE(46)
#define USE_ALL_48() USE_ALL_47() USE(47)
#define USE_ALL_49() USE_ALL_48() USE(48)
#define USE_ALL_50() USE_ALL_49() USE(49)
#define USE_ALL_51() USE_ALL_50() USE(50)
#define USE_ALL_52() USE_ALL_51() USE(51)
#define USE_ALL_53() USE_ALL_52() USE(52)
#define USE_ALL_54() USE_ALL_53() USE(53)
#define USE_ALL_55() USE_ALL_54() USE(54)
#define USE_ALL_56() USE_ALL_55() USE(55)
#define USE_ALL_57() USE_ALL_56() USE(56)
#define USE_ALL_58() USE_ALL_57() USE(57)
#define USE_ALL_59() USE_ALL_58() USE(58)
#define USE_ALL_60() USE_ALL_59() USE(59)
#define USE_ALL_61() USE_ALL_60() USE(60)
#define USE_ALL_62() USE_ALL_61() USE(61)
#define USE_ALL_63() USE_ALL_62() USE(62)
#define USE_ALL_64() USE_ALL_63() USE(63)
#define USE_ALL_65() USE_ALL_64() USE(64)
#define USE_ALL_66() USE_ALL_65() USE(65)
#define USE_ALL_67() USE_ALL_66() USE(66)
#define USE_ALL_68() USE_ALL_67() USE(67)
#define USE_ALL_69() USE_ALL_68() USE(68)
#define USE_ALL_70() USE_ALL_69() USE(69)
#define USE_ALL_71() USE_ALL_70() USE(70)
#define USE_ALL_72() USE_ALL_71() USE(71)
#define USE_ALL_73() USE_ALL_72() USE(72)
#define USE_ALL_74() USE_ALL_73() USE(73)
#define USE_ALL_75() USE_ALL_74() USE(74)
#define USE_ALL_76() USE_ALL_75() USE(75)
#define USE_ALL_77() USE_ALL_76() USE(76)
#define USE_ALL_78() USE_ALL_77() USE(77)
#define USE_ALL_79() USE_ALL_78() USE(78)
#define USE_ALL_80() USE_ALL_79() USE(79)
#define USE_ALL_81() USE_ALL_80() USE(80)
#define USE_ALL_82() USE_ALL_81() USE(81)
#define USE_ALL_83() USE_ALL_82() USE(82)
#define USE_ALL_84() USE_ALL_83() USE(83)
#define USE_ALL_85() USE_ALL_84() USE(84)
#define USE_ALL_86() USE_ALL_85() USE(85)
#define USE_ALL_87() USE_ALL_86() USE(86)
#define USE_ALL_88() USE_ALL_87() USE(87)
#define USE_ALL_89() USE_ALL_88() USE(88)
#define USE_ALL_90() USE_ALL_89() USE(89)
#define USE_ALL_91() USE_ALL_90() USE(90)
#define USE_ALL_92() USE_ALL_91() USE(91)
#define USE_ALL_93() USE_ALL_92() USE(92)
#define USE_ALL_94() USE_ALL_93() USE(93)
#define USE_ALL_95() USE_ALL_94() USE(94)
#define USE_ALL_96() USE_ALL_95() USE(95)
#define USE_ALL_97() USE_ALL_96() USE(96)
#define USE_ALL_98() USE_ALL_97() USE(97)
#define USE_ALL_99() USE_ALL_98() USE(98)
#define USE_ALL_100() USE_ALL_99() USE(99)
#define USE_UP_TO(n) EXPAND(CAT(USE_ALL_, n)())

static std::size_t g_total = 0;

#ifdef BENCH_REFLECTION
    #define USE(i) do \
    { \
        person_##i p{}; \
        json j; \
        refl::to_json(j, p); \
        g_total += j.dump().size(); \
        refl::from_json(j, p); \
    } while (0);
#else
    #define USE(i) do \
    { \
        person_##i p{}; \
        json j; \
        nlohmann::to_json(j, p); \
        g_total += j.dump().size(); \
        nlohmann::from_json(j, p); \
    } while (0);
#endif

int main()
{
    USE_UP_TO(BENCH_N)
#ifdef BENCH_REFLECTION
    std::printf("bench reflection BENCH_N=%d total=%zu\n", BENCH_N, g_total);
#else
    std::printf("bench macro     BENCH_N=%d total=%zu\n", BENCH_N, g_total);
#endif
    return 0;
}
