#!/usr/bin/env bash
# bench_scaling.sh — does the reflection path scale with the type count?
#
# bench_macro_vs_reflection.sh answers "what does reflection cost per type?" up
# to N=100 (its hand-written TU is capped there). This driver answers the
# follow-up the upstream adoption question actually turns on: does the cost stay
# LINEAR as N grows, or does template/reflection instantiation blow up?
#
# For each N it generates the TU with bench_scaling_gen.py and compiles it in
# both modes, reporting wall time, peak RSS, executable bytes, `size` text and
# `nm` symbol count. The marginal cost per type (delta between consecutive N)
# is the number to watch: a growing delta means superlinear scaling.
#
# Usage:
#   bash tests/static-reflection/bench_scaling.sh                  # default sweep
#   BENCH_N_SET="100 200" BENCH_RUNS=1 bash ...bench_scaling.sh     # smoke run
#   BENCH_MARKDOWN=1 bash ...bench_scaling.sh                       # + table
#
# Environment overrides:
#   BENCH_N_SET   whitespace list of N values   (default: "100 200 400 800 1600")
#   BENCH_OPT     optimization level            (default: "0")
#   BENCH_RUNS    compile runs per config, min kept (default: 2)
#   BENCH_MODES   modes to run                  (default: "macro refl2")
#   CXX           compiler binary               (default: g++-16)
#   OUT_DIR       artifact directory (gitignored) (default: build/scratch/scaling)
#   RESULTS_FILE  raw output file               (default: $OUT_DIR/scaling_results.txt)
#
# Requires GNU /usr/bin/time, size and nm. The generated TUs and binaries land
# in $OUT_DIR (gitignored); the authoritative session snapshot is committed
# under docs/static-reflection/data/ (see EVALUATION.md §5).
set -euo pipefail

BENCH_N_SET="${BENCH_N_SET:-100 200 400 800 1600}"
BENCH_OPT="${BENCH_OPT:-0}"
BENCH_RUNS="${BENCH_RUNS:-2}"
BENCH_MODES="${BENCH_MODES:-macro refl2}"
CXX="${CXX:-g++-16}"
OUT_DIR="${OUT_DIR:-build/scratch/scaling}"
RESULTS_FILE="${RESULTS_FILE:-${OUT_DIR}/scaling_results.txt}"
BENCH_MARKDOWN="${BENCH_MARKDOWN:-0}"
TIMEOUT_S="${TIMEOUT_S:-1800}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
GEN="${SCRIPT_DIR}/bench_scaling_gen.py"

command -v "${CXX}" >/dev/null 2>&1 || { echo "error: compiler '${CXX}' not found (try CXX=g++-16)" >&2; exit 1; }
[ -x /usr/bin/time ]             || { echo "error: GNU /usr/bin/time required" >&2; exit 1; }
command -v size >/dev/null 2>&1  || { echo "error: 'size' not found" >&2; exit 1; }
command -v nm   >/dev/null 2>&1  || { echo "error: 'nm' not found" >&2; exit 1; }
[ -f "${GEN}" ]                  || { echo "error: generator not found: ${GEN}" >&2; exit 1; }
command -v python3 >/dev/null 2>&1 || { echo "error: python3 required" >&2; exit 1; }

mkdir -p "${OUT_DIR}"

# --- header (reproducibility context) ---------------------------------------
{
    echo "# scaling sweep — generated by tests/static-reflection/bench_scaling.sh"
    echo "# date:      $(date -Iseconds)"
    echo "# host:      $(hostname)"
    echo "# toolchain: $(${CXX} --version | head -1)"
    echo "# git:       $(git -C "${REPO_ROOT}" rev-parse --short HEAD 2>/dev/null || echo unknown)"
    echo "# config:    N='${BENCH_N_SET}' O='${BENCH_OPT}' runs=${BENCH_RUNS} modes='${BENCH_MODES}'"
    echo "# src:       ${GEN} (struct shape matches bench_macro_vs_reflection.cpp)"
    echo "# units:     wall=s, rss=KB, exe/text=bytes, nm=symbols"
} > "${RESULTS_FILE}"

declare -A WALL RSS EXE TEXT NM

printf '%-7s %-8s %10s %10s %12s %12s %8s\n' \
    "N" "mode" "wall(s)" "rss(KB)" "exe(B)" "text(B)" "symbols" | tee -a "${RESULTS_FILE}"

for n in ${BENCH_N_SET}; do
    for mode in ${BENCH_MODES}; do
        src="${OUT_DIR}/n${n}_${mode}.cpp"
        bin="${OUT_DIR}/n${n}_${mode}"
        python3 "${GEN}" "${n}" "${mode}" "${src}"

        best_wall=""
        best_rss=""
        for _ in $(seq 1 "${BENCH_RUNS}"); do
            stats=$(timeout "${TIMEOUT_S}" /usr/bin/time -f "%e %M" \
                "${CXX}" -std=c++26 -freflection "-O${BENCH_OPT}" -I"${REPO_ROOT}/include" \
                -o "${bin}" "${src}" 2>&1 | tail -1) || {
                    echo "FAILED (timeout or compile error): N=${n} mode=${mode}" | tee -a "${RESULTS_FILE}"
                    best_wall=""; break
                }
            w=$(echo "${stats}" | awk '{print $1}')
            r=$(echo "${stats}" | awk '{print $2}')
            if [ -z "${best_wall}" ] || awk "BEGIN{exit !(${w} < ${best_wall})}"; then
                best_wall="${w}"; best_rss="${r}"
            fi
        done
        [ -n "${best_wall}" ] || continue

        exe=$(stat -c %s "${bin}")
        text=$(size -A "${bin}" | awk '$1==".text"{print $2}')
        syms=$(nm "${bin}" | wc -l)
        WALL["${n}:${mode}"]="${best_wall}"
        RSS["${n}:${mode}"]="${best_rss}"
        EXE["${n}:${mode}"]="${exe}"
        TEXT["${n}:${mode}"]="${text}"
        NM["${n}:${mode}"]="${syms}"

        printf '%-7s %-8s %10s %10s %12s %12s %8s\n' \
            "${n}" "${mode}" "${best_wall}" "${best_rss}" "${exe}" "${text}" "${syms}" | tee -a "${RESULTS_FILE}"
    done
done

# --- marginal cost per type (the linearity answer) --------------------------
{
    echo ""
    echo "# marginal cost per type (delta from the previous N in the sweep)"
    printf '# %-7s %-8s %12s %12s\n' "N" "mode" "wall/type" "rss/type"
} >> "${RESULTS_FILE}"

for mode in ${BENCH_MODES}; do
    prev_n=""
    for n in ${BENCH_N_SET}; do
        [ -n "${WALL["${n}:${mode}"]:-}" ] || continue
        if [ -n "${prev_n}" ] && [ -n "${WALL["${prev_n}:${mode}"]:-}" ]; then
            dw=$(awk "BEGIN{printf \"%.4f\", (${WALL["${n}:${mode}"]} - ${WALL["${prev_n}:${mode}"]}) / (${n} - ${prev_n})}")
            dr=$(awk "BEGIN{printf \"%.1f\", (${RSS["${n}:${mode}"]} - ${RSS["${prev_n}:${mode}"]}) / (${n} - ${prev_n})}")
            printf '%-8s %-8s %12s %12s\n' "${n}" "${mode}" "${dw}" "${dr}" >> "${RESULTS_FILE}"
        fi
        prev_n="${n}"
    done
done

tail -n +1 "${RESULTS_FILE}" | sed -n '/marginal cost/,$p'

if [ "${BENCH_MARKDOWN}" = "1" ]; then
    echo ""
    echo "| N | mode | wall (s) | RSS (KB) | exe (B) | .text (B) | symbols |"
    echo "|---:|---|---:|---:|---:|---:|---:|"
    for n in ${BENCH_N_SET}; do
        for mode in ${BENCH_MODES}; do
            [ -n "${WALL["${n}:${mode}"]:-}" ] || continue
            echo "| ${n} | ${mode} | ${WALL["${n}:${mode}"]} | ${RSS["${n}:${mode}"]} | ${EXE["${n}:${mode}"]} | ${TEXT["${n}:${mode}"]} | ${NM["${n}:${mode}"]} |"
        done
    done
fi

echo ""
echo "raw results: ${RESULTS_FILE}"
